<a href="https://colab.research.google.com/github/th900/Projeto-02/blob/main/Ci%C3%AAncia_de_dados_para_agronegocio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
import warnings

warnings.filterwarnings("ignore")

In [7]:
train_d = pd.read_csv('/content/treino.csv')

In [8]:
train_d.head(10)

          ID  Estimated_Insects_Count  ...  Season  Crop_Damage
0  F00000001                      188  ...       1            0
1  F00000003                      209  ...       2            1
2  F00000004                      257  ...       2            1
3  F00000005                      257  ...       2            1
4  F00000006                      342  ...       2            1
5  F00000008                      448  ...       2            1
6  F00000009                      448  ...       2            1
7  F00000010                      577  ...       1            2
8  F00000012                      731  ...       2            0
9  F00000020                     1132  ...       1            2

[10 rows x 10 columns]

In [9]:
train_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88858 entries, 0 to 88857
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       88858 non-null  object
 1   Estimated_Insects_Count  88858 non-null  int64
 2   Crop_Type                88858 non-null  int64
 3   Soil_Type                88858 non-null  int64
 4   Pesticide_Use_Category   88858 non-null  int64
 5   Number_Doses_Week        88858 non-null  int64
 6   Number_Weeks_Used        79858 non-null  float64
 7   Number_Weeks_Quit        88858 non-null  int64
 8   Season                   88858 non-null  int64
 9   Crop_Damage              88858 non-null  int64
dtypes: float64(1), int64(8), object(1)
memory usage: 6.8+ MB

In [11]:
train_d["Crop_Damage"].value_counts()

Crop_Damage
0    74238
1    12307
2     2313
Name: count, dtype: int64